added the ability to automatically detect the extension of the currents.config file and to look for the right file
currents-dev/cypress-cloud pull request #129
Opened 2023-05-12 06:33 UTC by I-vac

2023-05-12 06:36 UTC, I-vac commented
Had an issue with the currents.config file not loading, because in my project I use type:modules and the file had to be .cjs, but it was hardcoded to look only for .js . Saw some other people having the same issue as me and decided to try and fix it myself.

2023-05-16 16:12 UTC, agoldis commented
Thanks a lot @I-vac will take a look shortly

2023-05-30 06:02 UTC, agoldis requested changes
Thanks for submitting the PR @I-vac and sorry for taking so long to review. Please see my inline comments.

2023-05-30 06:04 UTC, agoldis commented on packages/cypress-cloud/lib/config/config.ts
> +  return filepaths;
Please take a look at [const fsConfig = require(resolvedPath);](https://github.com/currents-dev/cypress-cloud/blob/0599cba23af142b458da8cb690fac90a9b6bff82/packages/cypress-cloud/lib/config/config.ts#L46-L47)

- the return value should be a valid argument to `path.resolve` - an array of a path elements
- the resolved file can be `require`'d as a commonJS module
- 
A good validation can be a test that makes sure we can actually require different extenstions.

2023-06-27 19:56 UTC, closed without merging